apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- pvc.yaml
- worker-job.yaml
images:
- name: log-worker:v1
  newName: ghcr.io/beyzanurtiril/distributed-log-analysis
  newTag: 4494e2453870737f08fd0cae9c36c4f9f71a29cc
