apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- pvc.yaml
- worker-job.yaml
images:
- name: log-worker:v1
  newName: ghcr.io/beyzanurtiril/distributed-log-analysis
  newTag: 52057549232d80d40c8913f9e031eb1971b9646e
